name: Deploy to Maven Central

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Create Maven settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << EOF
          <settings>
            <servers>
              <server>
                <id>central</id>
                <username>${{ secrets.OSSRH_USERNAME }}</username>
                <password>${{ secrets.OSSRH_PASSWORD }}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>ossrh</id>
                <activation>
                  <activeByDefault>true</activeByDefault>
                </activation>
                <properties>
                  <gpg.executable>gpg</gpg.executable>
                  <gpg.passphrase>${{ secrets.GPG_PASSPHRASE }}</gpg.passphrase>
                  <gpg.useagent>false</gpg.useagent>
                </properties>
              </profile>
            </profiles>
          </settings>
          EOF
          # Debug: Show settings.xml (without sensitive info)
          sed 's/<password>.*<\/password>/<password>***<\/password>/' ~/.m2/settings.xml

      - name: Setup GPG
        run: |
          # Create gnupg directory with correct permissions
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          
          # Configure GPG for non-interactive use
          cat > ~/.gnupg/gpg.conf << EOF
          use-agent
          pinentry-mode loopback
          batch
          no-tty
          EOF
          
          # Configure GPG agent
          cat > ~/.gnupg/gpg-agent.conf << EOF
          allow-loopback-pinentry
          EOF
          
          # Set correct permissions
          chmod 600 ~/.gnupg/gpg.conf ~/.gnupg/gpg-agent.conf
          
          # Write key to file with proper line endings
          # This preserves line breaks and formatting of the key
          echo -e "${{ secrets.GPG_PRIVATE_KEY }}" > private.key
          gpg --batch --import private.key
          rm private.key
          
          # Display imported key for verification
          gpg --list-secret-keys --keyid-format LONG
          
          # Get key ID for signing
          KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d'/' -f2)
          echo "Using GPG key: $KEY_ID"
          
          # Test signing
          echo "test" > test.txt
          gpg --batch --yes --passphrase "${{ secrets.GPG_PASSPHRASE }}" --pinentry-mode loopback -u $KEY_ID --sign test.txt
          gpg --verify test.txt.gpg

      - name: Build and deploy
        run: |
          echo "Testing Central credentials..."
          curl -v -u "${{ secrets.OSSRH_USERNAME }}:${{ secrets.OSSRH_PASSWORD }}" https://central.sonatype.com/api/v1/publishing/verify
          # Test credentials with Maven
          mvn help:effective-settings
          # Deploy with debug
          mvn clean deploy -Psign-artifacts --batch-mode --no-transfer-progress -X
